[build-system]
requires = ["setuptools>=68", "wheel", "Cython>=0.29.28", "numpy>=1.24"]
build-backend = "setuptools.build_meta"
[tool.setuptools]
package-dir = { "" = "neural_stpp" }

[tool.setuptools.packages.find]
where   = ["neural_stpp"]
include = ["neural_stpp", "neural_stpp.*"]
